v5版本协议兼容
hyperf/mqtt-server-incubator pull request #4
Opened 2023-01-31 01:00 UTC by yexueduxing

增加v5版本协议兼容支持

2023-02-03 00:20 UTC, sy-records requested changes

2023-02-03 00:20 UTC, sy-records commented on src/MQTTServer.php
> +            }
这里用上下文存储协议等级不对，因为connect、publish、sub... 这些请求是分开的。 应该使用cache

2023-02-18 19:22 UTC, huangzhhui commented
为啥从 Context 储存 ProtocolLevel 改成了从 Response Attribute ？

2023-02-20 00:33 UTC, yexueduxing commented
因为cache的缓存处理依赖得了fd，而fd存储在response中，也是想保持协议和fd的存储操作一定的一致性，所以就没有再使用context去存储。

2023-09-16 14:05 UTC, closed without merging